project_id = "weplan"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]

[db]
port = 54322
major_version = 17

[studio]
enabled = true
port = 54323

[functions.pin-crypto]
verify_jwt = false
